test:
  adapter: postgresql
  encoding: unicode
  database: minibox_test
  pool: 5
  username: ice
  password: "ice123"

development:
  adapter: postgresql
  encoding: unicode
  database: minibox
  pool: 5
  username: ice
  password: "ice123"

production:
  adapter: postgresql
  encoding: unicode
  database: minibox
  pool: 5
